language: php

php:
  - 5.4

services:
  - memcached
  - mongodb
  - redis-server

before_script:
  - time ./.travis_setup.sh

script: php app/check.php && ./bin/qa_client_ci.sh && ./bin/qa_behat.sh

